name: lcd_data
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - requests
  - shapely
  - xarray
  - pip:
      - git+https://github.com/jankazil/lcd-data
